### PR TITLE
typos

### PR DESCRIPTION
**Pull request by pfeerick**
Just some minor proofreading fixes.

EdgeTX 2.6? Don't you mean 2.9 if this is for the T15?

### CODE REVIEW

**Comment by druckgott** [comment]
? you did the pull requests on your repository not on my one. I alrady did some updates in the readme file

**Comment by pfeerick** [comment]
Ah, fking useless github defaulting to own not fork repo ... needs to stick to one or the other, not change on a whim!

**Comment by druckgott** [comment]
ok I have fixed all the points so maybe we can commit it to the edgetx lua script list would be nice.

**Comment by pfeerick** [comment]
Looks like you updated the example screenshot also, which was going to be my only comment over there, so fine by me.

**Pull request closed without merging**
